# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Spring 2020'
tagline:          'The GAP Infrastructure'
description:      '23<sup>rd</sup> to 27<sup>th</sup> March 2020'
location:         'Scotland'
url:              https://www.gapdays.de
baseurl:          /gapdays2020-spring


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
